graph LR
  att_考勤打卡["att-考勤打卡<br/><small>05-人事系统域</small>"]
  bad_不良品["bad-不良品<br/><small>02-生产铸造域</small>"]
  dailyreport_日报任务["dailyreport-日报任务<br/><small>05-人事系统域</small>"]
  device_设备装置["device-设备装置<br/><small>03-质量技术域</small>"]
  django_auth框架["django-auth框架<br/><small>07-框架表</small>"]
  equipment_设备["equipment-设备<br/><small>03-质量技术域</small>"]
  fixture_工装夹具["fixture-工装夹具<br/><small>03-质量技术域</small>"]
  hr_人力能力["hr-人力能力<br/><small>05-人事系统域</small>"]
  inspection_质量检验["inspection-质量检验<br/><small>03-质量技术域</small>"]
  knife_刀具["knife-刀具<br/><small>03-质量技术域</small>"]
  logistics_物流["logistics-物流<br/><small>01-供应链域</small>"]
  maintenance_维修保养["maintenance-维修保养<br/><small>03-质量技术域</small>"]
  misc_alarm["misc-alarm<br/><small>06-其他定制</small>"]
  misc_definition["misc-definition<br/><small>06-其他定制</small>"]
  misc_go["misc-go<br/><small>06-其他定制</small>"]
  misc_management["misc-management<br/><small>06-其他定制</small>"]
  misc_site["misc-site<br/><small>06-其他定制</small>"]
  misc_ticket["misc-ticket<br/><small>06-其他定制</small>"]
  newscheduling_新排程["newscheduling-新排程<br/><small>02-生产铸造域</small>"]
  order_订单["order-订单<br/><small>04-订单项目域</small>"]
  payment_付款["payment-付款<br/><small>01-供应链域</small>"]
  plan_生产计划["plan-生产计划<br/><small>02-生产铸造域</small>"]
  process_工艺技术["process-工艺技术<br/><small>03-质量技术域</small>"]
  product_产品["product-产品<br/><small>03-质量技术域</small>"]
  production_生产["production-生产<br/><small>02-生产铸造域</small>"]
  project_项目["project-项目<br/><small>04-订单项目域</small>"]
  purchase_采购["purchase-采购<br/><small>01-供应链域</small>"]
  qrcode_二维码追溯["qrcode-二维码追溯<br/><small>02-生产铸造域</small>"]
  settlement_结算["settlement-结算<br/><small>01-供应链域</small>"]
  shift_班次["shift-班次<br/><small>02-生产铸造域</small>"]
  supplier_供应商["supplier-供应商<br/><small>01-供应链域</small>"]
  system_用户权限["system-用户权限<br/><small>05-人事系统域</small>"]
  tf_TF铸造["tf-TF铸造<br/><small>02-生产铸造域</small>"]
  tool_工具工装["tool-工具工装<br/><small>03-质量技术域</small>"]
  warehouse_仓储["warehouse-仓储<br/><small>01-供应链域</small>"]
  purchase_采购 -->|16关联| system_用户权限
  warehouse_仓储 -->|10关联| purchase_采购
  project_项目 -->|10关联| purchase_采购
  order_订单 -->|8关联| purchase_采购
  equipment_设备 -->|5关联| system_用户权限
  django_auth框架 -->|5关联| system_用户权限
  payment_付款 -->|4关联| purchase_采购
  payment_付款 -->|4关联| settlement_结算
  settlement_结算 -->|4关联| purchase_采购
  settlement_结算 -->|4关联| payment_付款
  supplier_供应商 -->|4关联| purchase_采购
  equipment_设备 -->|4关联| device_设备装置
  hr_人力能力 -->|4关联| system_用户权限
  knife_刀具 -->|3关联| production_生产
  system_用户权限 -->|3关联| django_auth框架
  device_设备装置 -->|3关联| equipment_设备
  dailyreport_日报任务 -->|3关联| system_用户权限
  qrcode_二维码追溯 -->|2关联| production_生产
  maintenance_维修保养 -->|2关联| device_设备装置
  product_产品 -->|2关联| qrcode_二维码追溯
  dailyreport_日报任务 -->|2关联| misc_go
  hr_人力能力 -->|2关联| device_设备装置
  att_考勤打卡 -->|2关联| system_用户权限
  logistics_物流 -->|1关联| purchase_采购
  bad_不良品 -->|1关联| system_用户权限
  plan_生产计划 -->|1关联| order_订单
  plan_生产计划 -->|1关联| hr_人力能力
  plan_生产计划 -->|1关联| production_生产
  production_生产 -->|1关联| bad_不良品
  production_生产 -->|1关联| qrcode_二维码追溯
  qrcode_二维码追溯 -->|1关联| order_订单
  qrcode_二维码追溯 -->|1关联| bad_不良品
  qrcode_二维码追溯 -->|1关联| hr_人力能力
  qrcode_二维码追溯 -->|1关联| device_设备装置
  tf_TF铸造 -->|1关联| hr_人力能力
  device_设备装置 -->|1关联| django_auth框架
  device_设备装置 -->|1关联| system_用户权限
  device_设备装置 -->|1关联| inspection_质量检验
  equipment_设备 -->|1关联| inspection_质量检验
  fixture_工装夹具 -->|1关联| device_设备装置
  knife_刀具 -->|1关联| hr_人力能力
  process_工艺技术 -->|1关联| bad_不良品
  process_工艺技术 -->|1关联| qrcode_二维码追溯
  tool_工具工装 -->|1关联| production_生产
  project_项目 -->|1关联| system_用户权限
  hr_人力能力 -->|1关联| newscheduling_新排程
  hr_人力能力 -->|1关联| knife_刀具
  hr_人力能力 -->|1关联| bad_不良品
  system_用户权限 -->|1关联| bad_不良品
  misc_alarm -->|1关联| device_设备装置
  bad_不良品 -->|1关联| qrcode_二维码追溯
  newscheduling_新排程 -->|1关联| hr_人力能力
  newscheduling_新排程 -->|1关联| device_设备装置
  newscheduling_新排程 -->|1关联| system_用户权限
  shift_班次 -->|1关联| system_用户权限
  device_设备装置 -->|1关联| newscheduling_新排程
  maintenance_维修保养 -->|1关联| system_用户权限
  process_工艺技术 -->|1关联| product_产品
  process_工艺技术 -->|1关联| system_用户权限
  att_考勤打卡 -->|1关联| hr_人力能力
  system_用户权限 -->|1关联| misc_ticket
  misc_site -->|1关联| misc_management
  misc_site -->|1关联| misc_definition